DROP TABLE #input;
CREATE TABLE #input (i VARCHAR(500));
BULK INSERT #input
    FROM 'C:\Temp\input.txt'
    WITH
    (
    FIRSTROW = 1,
    ROWTERMINATOR = '\n\n',   --Use to shift the control to next row + include blank line
    TABLOCK
    );


WITH CTE_AZ (i,az) AS (
select i,LOWER('ABCDEFGHIJKLMNOPQRSTUVWXYZ')
from #input 
),
CTE_AZExists (input, A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z) AS (
SELECT 
i,
CASE WHEN i LIKE '%'+SUBSTRING(az,1,1)+'%' THEN 1 ELSE 0 END,
CASE WHEN i LIKE '%'+SUBSTRING(az,2,1)+'%' THEN 1 ELSE 0 END,
CASE WHEN i LIKE '%'+SUBSTRING(az,3,1)+'%' THEN 1 ELSE 0 END,
CASE WHEN i LIKE '%'+SUBSTRING(az,4,1)+'%' THEN 1 ELSE 0 END,
CASE WHEN i LIKE '%'+SUBSTRING(az,5,1)+'%' THEN 1 ELSE 0 END,
CASE WHEN i LIKE '%'+SUBSTRING(az,6,1)+'%' THEN 1 ELSE 0 END,
CASE WHEN i LIKE '%'+SUBSTRING(az,7,1)+'%' THEN 1 ELSE 0 END,
CASE WHEN i LIKE '%'+SUBSTRING(az,8,1)+'%' THEN 1 ELSE 0 END,
CASE WHEN i LIKE '%'+SUBSTRING(az,9,1)+'%' THEN 1 ELSE 0 END,
CASE WHEN i LIKE '%'+SUBSTRING(az,10,1)+'%' THEN 1 ELSE 0 END,
CASE WHEN i LIKE '%'+SUBSTRING(az,11,1)+'%' THEN 1 ELSE 0 END,
CASE WHEN i LIKE '%'+SUBSTRING(az,12,1)+'%' THEN 1 ELSE 0 END,
CASE WHEN i LIKE '%'+SUBSTRING(az,13,1)+'%' THEN 1 ELSE 0 END,
CASE WHEN i LIKE '%'+SUBSTRING(az,14,1)+'%' THEN 1 ELSE 0 END,
CASE WHEN i LIKE '%'+SUBSTRING(az,15,1)+'%' THEN 1 ELSE 0 END,
CASE WHEN i LIKE '%'+SUBSTRING(az,16,1)+'%' THEN 1 ELSE 0 END,
CASE WHEN i LIKE '%'+SUBSTRING(az,17,1)+'%' THEN 1 ELSE 0 END,
CASE WHEN i LIKE '%'+SUBSTRING(az,18,1)+'%' THEN 1 ELSE 0 END,
CASE WHEN i LIKE '%'+SUBSTRING(az,19,1)+'%' THEN 1 ELSE 0 END,
CASE WHEN i LIKE '%'+SUBSTRING(az,20,1)+'%' THEN 1 ELSE 0 END,
CASE WHEN i LIKE '%'+SUBSTRING(az,21,1)+'%' THEN 1 ELSE 0 END,
CASE WHEN i LIKE '%'+SUBSTRING(az,22,1)+'%' THEN 1 ELSE 0 END,
CASE WHEN i LIKE '%'+SUBSTRING(az,23,1)+'%' THEN 1 ELSE 0 END,
CASE WHEN i LIKE '%'+SUBSTRING(az,24,1)+'%' THEN 1 ELSE 0 END,
CASE WHEN i LIKE '%'+SUBSTRING(az,25,1)+'%' THEN 1 ELSE 0 END,
CASE WHEN i LIKE '%'+SUBSTRING(az,26,1)+'%' THEN 1 ELSE 0 END
FROM CTE_AZ)
select '1' AS Part, SUM(A+B+C+D+E+F+G+H+I+J+K+L+M+N+O+P+Q+R+S+T+U+V+W+X+Y+Z) AS Result
from CTE_AZExists